# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from mail import Sender
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor, QIcon
from PyQt5.QtWidgets import QMessageBox, QAction, QMainWindow, QLineEdit
from send_mail import Ui_MainWindow_sendmail


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 550)
        MainWindow.setMinimumSize(QtCore.QSize(750, 550))
        MainWindow.setMaximumSize(QtCore.QSize(750, 550))
        MainWindow.setWhatsThis("")
        MainWindow.setStyleSheet("background: #6ED0F6;\n"
"  color: #fff;\n"
"  font-family: \'Raleway\', sans-serif;\n"
"  -webkit-font-smoothing: antialiased;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_sing_in = QtWidgets.QLabel(self.centralwidget)
        self.label_sing_in.setGeometry(QtCore.QRect(300, 150, 171, 91))
        self.label_sing_in.setStyleSheet("\n"
"  display: inline-block;\n"
"  font-size: 30px;\n"
"  font-weight: 800;\n"
"  opacity: .5;\n"
"  margin-bottom: 30px;\n"
"  text-transform: uppercase;\n"
"margin-right: 20px;")
        self.label_sing_in.setObjectName("label_sing_in")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(240, 210, 281, 61))
        self.lineEdit_email.setWhatsThis("")
        self.lineEdit_email.setStyleSheet("background: #fff;\n"
"color: rgb(0, 0, 0);\n"
"  border: none;\n"
"  border-radius: 8px;\n"
"  font-size: 27px;\n"
"  font-family: \'Raleway\', sans-serif;\n"
"  height: 72px;\n"
"  width: 99.5%;\n"
"  margin-bottom: 10px;\n"
"  opacity: 1;\n"
"  text-indent: 20px;\n"
"  transition: all .2s ease-in-out;\n"
"\n"
"")
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_email.setPlaceholderText("Email")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(240, 270, 281, 61))
        self.lineEdit_password.setStyleSheet("color: rgb(0, 0, 0);\n"
"  background: #fff;\n"
"  border: none;\n"
"  border-radius: 8px;\n"
"  font-size: 27px;\n"
"  font-family: \'Raleway\', sans-serif;\n"
"  height: 72px;\n"
"  width: 99.5%;\n"
"  margin-bottom: 10px;\n"
"  opacity: 1;\n"
"  text-indent: 20px;\n"
"  transition: all .2s ease-in-out;\n"
"\n"
"")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_password.setPlaceholderText("Password")
        self.pushButton_singin = QtWidgets.QPushButton(self.centralwidget)
        self.pass_mode = False
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.watch_pass = self.lineEdit_password.addAction(QIcon('pass_icone.png'), QLineEdit.ActionPosition.TrailingPosition)
        self.watch_pass.triggered.connect(self.change_pass_mode)
        self.pushButton_singin.setGeometry(QtCore.QRect(290, 330, 181, 71))
        self.pushButton_singin.setStyleSheet("\n"
"background: #079BCF;\n"
"  border: none;\n"
"  border-radius: 8px;\n"
"  color: #fff;\n"
"  font-family: \'Raleway\', sans-serif;\n"
"  font-size: 27px;\n"
"  height: 72px;\n"
"  width: 100%;\n"
"  margin-bottom: 10px;\n"
"  overflow: hidden;\n"
"  transition: all .3s cubic-bezier(.6,0,.4,1);\n"
"cursor: pointer;\n"
"")
        self.pushButton_singin.setObjectName("pushButton_singin")
        self.pushButton_singin.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Email"))
        self.label_sing_in.setText(_translate("MainWindow", "Sign in"))
        self.lineEdit_email.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        # self.lineEdit_password.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>password</p></body></html>"))
        # self.pushButton_singin.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_singin.setText(_translate("MainWindow", "sign in"))

    def add_functions(self):
        self.pushButton_singin.clicked.connect(self.sign_in)


    def sign_in(self):
        try:
            email = self.lineEdit_email.text()
            password = self.lineEdit_password.text()
            sender = Sender(email, password)
            if sender:
                MainWindow.close()
                self.MainWindow = QtWidgets.QMainWindow()
                self.ui = Ui_MainWindow_sendmail(sender)
                self.ui.setupUi(self.MainWindow)
                self.MainWindow.show()
        except Exception as e:
            print(e)
            self.lineEdit_email.clear()
            self.lineEdit_password.clear()
            error = QMessageBox()
            error.setWindowTitle("Ошибка входа")
            error.setText("Неверный email или пароль")
            error.setIcon(QMessageBox.Warning)
            error.exec_()

    def change_pass_mode(self):
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password) if self.pass_mode else \
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.pass_mode = not(self.pass_mode)



if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
