# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor


class Ui_Form_received_mail(object):
    def setupUi(self, Form_received_mail):
        Form_received_mail.setObjectName("Form_received_mail")
        Form_received_mail.resize(400, 300)
        Form_received_mail.setStyleSheet("background: #6ED0F6;\n"
"color: #fff;\n"
"font-family: \\\'Raleway\\\', sans-serif;\n"
"-webkit-font-smoothing: antialiased;")
        self.pushButton_decode_mail = QtWidgets.QPushButton(Form_received_mail)
        self.pushButton_decode_mail.setGeometry(QtCore.QRect(270, 243, 121, 51))
        self.pushButton_decode_mail.setStyleSheet("background: #079BCF;\n"
"border: none;\n"
"border-radius: 16px;\n"
"color: #fff;\n"
"cursor: pointer;\n"
"font-family: \\\'Raleway\\\', sans-serif;\n"
"font-size: 15px;\n"
"height: 30px;\n"
"width: 100%;\n"
"margin-bottom: 10px;\n"
"overflow: hidden;\n"
"")
        self.pushButton_decode_mail.setObjectName("pushButton_decode_mail")
        self.pushButton_decode_mail.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.textBrowser_received_text = QtWidgets.QTextBrowser(Form_received_mail)
        self.textBrowser_received_text.setGeometry(QtCore.QRect(10, 100, 256, 192))
        self.textBrowser_received_text.setStyleSheet("background: #fff;\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-radius: 8px;\n"
"font-size: 22px;\n"
"font-family: \\\'Raleway\\\', sans-serif;\n"
"height: 72px;\n"
"width: 99.5%;\n"
"margin-bottom: 10px;\n"
"opacity: 1;\n"
"text-indent: 20px;\n"
"transition: all .2s ease-in-out;")
        self.textBrowser_received_text.setObjectName("textBrowser_received_text")
        self.lineEdit_received_from = QtWidgets.QLineEdit(Form_received_mail)
        self.lineEdit_received_from.setReadOnly(True)
        self.lineEdit_received_from.setGeometry(QtCore.QRect(10, 10, 256, 41))
        self.lineEdit_received_from.setStyleSheet("background: #fff;\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-radius: 8px;\n"
"font-size: 20px;\n"
"font-family: \\\'Raleway\\\', sans-serif;\n"
"height: 72px;\n"
"width: 99.5%;\n"
"margin-bottom: 10px;\n"
"opacity: 1;\n"
"text-indent: 20px;\n"
"transition: all .2s ease-in-out;")
        self.lineEdit_received_from.setObjectName("lineEdit_received_from")
        self.lineEdit_received_subject = QtWidgets.QLineEdit(Form_received_mail)
        self.lineEdit_received_subject.setReadOnly(True)
        self.lineEdit_received_subject.setGeometry(QtCore.QRect(10, 60, 200, 41))
        self.lineEdit_received_subject.setStyleSheet("background: #fff;\n"
"color: rgb(0, 0, 0);\n"
"border: none;\n"
"border-radius: 8px;\n"
"font-size: 20px;\n"
"font-family: \\\'Raleway\\\', sans-serif;\n"
"height: 72px;\n"
"width: 99.5%;\n"
"margin-bottom: 10px;\n"
"opacity: 1;\n"
"text-indent: 20px;\n"
"transition: all .2s ease-in-out;")
        self.lineEdit_received_subject.setObjectName("lineEdit_received_subject")

        self.retranslateUi(Form_received_mail)
        QtCore.QMetaObject.connectSlotsByName(Form_received_mail)

    def retranslateUi(self, Form_received_mail):
        _translate = QtCore.QCoreApplication.translate
        Form_received_mail.setWindowTitle(_translate("Form_received_mail", "Form"))
        self.pushButton_decode_mail.setText(_translate("Form_received_mail", "Decode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_received_mail = QtWidgets.QWidget()
    ui = Ui_Form_received_mail()
    ui.setupUi(Form_received_mail)
    Form_received_mail.show()
    sys.exit(app.exec_())
